// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7X9Ej84tIRBieN0FXMCleEPSMUoWEB68',
    appId: '1:409107405882:web:9eb380be20fbd15ad6a903',
    messagingSenderId: '409107405882',
    projectId: 'reading-room-management-5475',
    authDomain: 'reading-room-management-5475.firebaseapp.com',
    storageBucket: 'reading-room-management-5475.firebasestorage.app',
    measurementId: 'G-K1JKFS09YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwOQ3ZTyH6UXI0UiC8oWKEtBj3ULr2TLo',
    appId: '1:409107405882:android:8d5599bb9c947b8fd6a903',
    messagingSenderId: '409107405882',
    projectId: 'reading-room-management-5475',
    storageBucket: 'reading-room-management-5475.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9TT9aOyeLnBcjcYu5PlIhr2Mn2hopXP0',
    appId: '1:409107405882:ios:8e92d2fe5ce144b5d6a903',
    messagingSenderId: '409107405882',
    projectId: 'reading-room-management-5475',
    storageBucket: 'reading-room-management-5475.firebasestorage.app',
    iosBundleId: 'com.example.librarymanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9TT9aOyeLnBcjcYu5PlIhr2Mn2hopXP0',
    appId: '1:409107405882:ios:8e92d2fe5ce144b5d6a903',
    messagingSenderId: '409107405882',
    projectId: 'reading-room-management-5475',
    storageBucket: 'reading-room-management-5475.firebasestorage.app',
    iosBundleId: 'com.example.librarymanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7X9Ej84tIRBieN0FXMCleEPSMUoWEB68',
    appId: '1:409107405882:web:9570d85fdf13263dd6a903',
    messagingSenderId: '409107405882',
    projectId: 'reading-room-management-5475',
    authDomain: 'reading-room-management-5475.firebaseapp.com',
    storageBucket: 'reading-room-management-5475.firebasestorage.app',
    measurementId: 'G-GFZFX808JL',
  );
}
